# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Task8 (iOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Task8 (iOS)
pod 'SQLite.swift', '~> 0.12.0'
end

target 'Task8 (macOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Task8 (macOS)

end
